### ISSUE TITLE
Select Target Framework for the GUI

### ISSUE THREAD

**Issue by CharliePoole** [Test-Centric/test-centric-gui#1]
I know it's strange to have an issue before the initial upload, but anyway...

The old GUI code on which I based this targets .NET 2.0. That made sense with NUnit V2 because the default was to run test code in process. If we want to allow .NET 2.0 code using .NET 2.0 in process, then the GUI process has to be 2.0 as well.

For the new TestCentric GUI, I'm not sure that makes sense. The default is to run each assembly in a separate process, although you can change the settings to run in one separate process or in process. I'd like to run in a more recent framework and I'm thinking of 4.5.

IF we did that, the GUI could only run on machines with .NET 4.5 or higher. I don't see that as an issue. Does anyone else?

If the user forced a .NET 2.0 - 4.0 test to run in process, it would be running under .NET 4.5. Again, that doesn't seem to be a problem so long as it isn't the default. We might want to issue a warning if the user changed the default to running in-process. As an alternative, we could consider making in-process execution unavailable, but it's often handy for debugging.

What does everyone think? Is 4.5 the right compromise on level of framework required?

PS: If we don't resolve this right away, I'll go ahead with the initial upload, which uses 2.0.

**Comment by immeraufdemhund** [comment]
I believe we had a similar discussion a while ago and some people mentioned that linux by default had .net 4.5 now. I'd rather see 4.5 too personally (4.5.2 to make sure that one security issue is fixed)

**Comment by CharliePoole** [comment]
That makes sense to me. How do you think we should handle the situation where the user asks to run a .NET version test < the version we are using in process?

**Comment by mikkelbu** [comment]
I'm fine with 4.5, and I think it is a good idea with the warning if running in-process
(wrt. the default on Linux I found this [Mono 4.0.0 Release Notes](http://www.mono-project.com/docs/about-mono/releases/4.0.0/#dropped-support-for-old-frameworks), so 4.5 has been the default since 2015 it seems).

**Comment by immeraufdemhund** [comment]
...does it not work? I've made .net 2.0 libraries and consumed them in .net 4.5 applications... I don't see what the problem is.

**Comment by CharliePoole** [comment]
The warning would be something like... "Your code will all run under .NET 4.5 [or whatever we use]. This works for most people, but we're just sayin' in case it doesn't work for you."

Some apps need to be tested under their actual target frameworks. In fact, NUnit has always been one of them.

**Comment by CharliePoole** [comment]
BTW, I've switched my yet-to-be-uploaded code to target 4.5. That got rid of the private versions of Linq and the need for our own definition of `ExtensionAttribute`. We can talk about 4.5.2 as a further step if folks want to.

**Comment by CharliePoole** [comment]
We are currently targeting 4.5 and there's a separate issue for the in-process warning, so I'm closing this.
